version: "3.8"

services:
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.local
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - network
networks:
  network:
volumes:
  db:
